// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvyM9sX57Sq1Fvx2_Bf9DfY-9eWOtP-8M',
    appId: '1:879225500100:web:42ecbd82c720478aba3491',
    messagingSenderId: '879225500100',
    projectId: 'authentication-practise-d6829',
    authDomain: 'authentication-practise-d6829.firebaseapp.com',
    storageBucket: 'authentication-practise-d6829.appspot.com',
    measurementId: 'G-FDJ3558J3C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgQVAZRV8g-SVFU2KzWp5oMLsIuefzn4g',
    appId: '1:879225500100:android:ad21eb5f1f6861e2ba3491',
    messagingSenderId: '879225500100',
    projectId: 'authentication-practise-d6829',
    storageBucket: 'authentication-practise-d6829.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXxC6AYL_nlpuF8V2HdrYCM4Wu5tdtnVQ',
    appId: '1:879225500100:ios:9f97aafae9d41a4eba3491',
    messagingSenderId: '879225500100',
    projectId: 'authentication-practise-d6829',
    storageBucket: 'authentication-practise-d6829.appspot.com',
    iosBundleId: 'com.example.googleAuthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXxC6AYL_nlpuF8V2HdrYCM4Wu5tdtnVQ',
    appId: '1:879225500100:ios:ed1606d33bf381bcba3491',
    messagingSenderId: '879225500100',
    projectId: 'authentication-practise-d6829',
    storageBucket: 'authentication-practise-d6829.appspot.com',
    iosBundleId: 'com.example.googleAuthentication.RunnerTests',
  );
}
